name: octopod
services:

  app:
    build:
      context: ./js/app
      dockerfile: Dockerfile

  studio:
    build:
      context: ./js/studio
      dockerfile: Dockerfile
    ports:
      - "18890:80"

  api:
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROXY_PASS_ROOT=/api
      - POSTGRES_DSN=${POSTGRES_DSN}
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    entrypoint: ["rq", "worker", "--with-scheduler"]
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "18888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - api
      - studio
