"""Add UMA Auth fields for refresh to the user

Revision ID: 0072e753317a
Revises: 48da3d12307b
Create Date: 2024-09-12 13:06:33.327258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0072e753317a"
down_revision: Union[str, None] = "48da3d12307b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("nwc_refresh_token", sa.String(), nullable=True))
    op.add_column("user", sa.Column("nwc_expires_at", sa.Integer(), nullable=True))
    op.add_column(
        "user", sa.Column("access_token_expires_at", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "access_token_expires_at")
    op.drop_column("user", "nwc_expires_at")
    op.drop_column("user", "nwc_refresh_token")
    # ### end Alembic commands ###
