"""add-vector-embedding

Revision ID: 0dd5dae34621
Revises: 1bc31ff19e88
Create Date: 2024-09-10 22:32:31.891150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector  # type: ignore


# revision identifiers, used by Alembic.
revision: str = "0dd5dae34621"
down_revision: Union[str, None] = "1bc31ff19e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "podclip",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("podclip", "embedding")
    # ### end Alembic commands ###
