"""add-profile-fields

Revision ID: 48da3d12307b
Revises: 0dd5dae34621
Create Date: 2024-09-11 20:57:12.686796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48da3d12307b"
down_revision: Union[str, None] = "0dd5dae34621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("picture_url", sa.String(), nullable=True))

    op.execute(
        """
        UPDATE public.user
        SET first_name = 'John',
            last_name = 'Doe'
        WHERE first_name IS NULL AND last_name IS NULL;
        """
    )

    op.execute(
        """
        ALTER TABLE public.user ALTER COLUMN first_name SET NOT NULL;
        """
    )
    op.execute(
        """
        ALTER TABLE public.user ALTER COLUMN last_name SET NOT NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "picture_url")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
