name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./core
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install pipenv
      run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
    - name: Cache pipenv virtualenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    
    - name: Install dependencies
      run: pipenv install --dev

    - name: Run tests
      run: PYTHONPATH=. pipenv run pytest

    - name: Run black
      run: PYTHONPATH=. pipenv run black --check .
    
    - name: Run ruff
      run: PYTHONPATH=. pipenv run ruff check .

    - name: Run mypy
      run: PYTHONPATH=. pipenv run mypy .
